# Generated by Django 2.1.2 on 2018-10-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0002_auto_20180620_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='tweet_images/'),
        ),
    ]
